# This workflow will build a java project with maven
name: Build project for cms events

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Setting up java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1
      - name: Test and verify module
        run: mvn --batch-mode --update-snapshots verify && mvn test
        env:
          GITHUB_USERNAME: rohan23chhabra
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

